version: "3"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./smokeping-config:/config
      - ./smokeping-data:/data
    ports:
      - 80:80
    restart: unless-stopped
