#!/bin/bash

# Auto-install xkcdpass if it isn't already present
if ! command -v xkcdpass &> /dev/null; then
  echo "xkcdpass not found, installing..." >&2
  sudo apt install -y xkcdpass || exit 1
fi

if ! command -v shuf &> /dev/null; then
  echo "Error: shuf not found.  It should be part of coreutils."
  exit 1
fi


# Generate the password
echo "$(xkcdpass -n 3) $(shuf -i 100-999 -n 1)"  | sed 's/ /-/g'
